export { default as patientAuthRoute } from './patient/patient.auth.route.js'
export { default as providerAuthRoute } from './provider/provider.auth.route.js'
export { default as authService } from './auth.service.js'
export { default as authValidation } from './auth.validation.js'
export { default as googleAuthRoute } from './google/googleAuth.route.js'
